/*
 * Auto-generated by tools/export_model_c.py
 * Meta: {"source": "ml_gate_logreg", "n_features": 16, "feature_names": ["w_b_idx", "f_b_idx", "delta_b", "rx_dt_ms", "w_hr", "f_hr", "hr_gap", "w_spo2", "f_spo2", "w_wf_std", "w_wf_prom", "w_wf_df", "w_wf_pec", "f_wf_std", "f_wf_prom", "f_wf_df"], "train_feature_cols": ["w_b_idx", "f_b_idx", "delta_b", "rx_dt_ms", "w_hr", "f_hr", "hr_gap", "w_spo2", "f_spo2"], "intercept": 0.24986273867775008, "train_sessions": ["exp11", "exp12", "exp13", "exp14", "exp15", "exp16", "exp17", "exp18", "exp19", "exp20", "exp21", "exp22", "exp23", "exp24", "exp25", "exp26", "exp27", "exp28", "exp29", "exp30", "exp31", "exp32", "exp33", "exp34", "exp35", "exp36", "exp37", "exp38", "exp39", "exp40", "exp41", "exp42", "exp43", "exp44", "exp45", "exp46", "exp47", "exp48", "exp49", "exp50", "exp51"]}
 */
#include "lgbm_model.h"
#include <math.h>

#define LGBM_N_FEATURES 16

static const float s_mean[LGBM_N_FEATURES] = {
    57.66557377f, 62.09016393f, 4.42459016f, 467.80163934f,
    53.23606557f, 64.31147541f, 12.50491803f, 94.23278689f,
    98.10163934f, 0.00000000f, 0.00000000f, 0.00000000f,
    0.00000000f, 0.00000000f, 0.00000000f, 0.00000000f
};

static const float s_scale[LGBM_N_FEATURES] = {
    2.13394772f, 2.30538962f, 3.11764706f, 127.83919842f,
    4.42051969f, 7.40257152f, 6.30228754f, 6.45246735f,
    3.92881294f, 1.00000000f, 1.00000000f, 1.00000000f,
    1.00000000f, 1.00000000f, 1.00000000f, 1.00000000f
};

static const float s_coef[LGBM_N_FEATURES] = {
    0.05027889f, 0.01392106f, -0.02412045f, -0.70888603f,
    0.18226451f, -0.35328259f, 0.06786999f, 0.47885816f,
    0.39784636f, 0.00000000f, 0.00000000f, 0.00000000f,
    0.00000000f, 0.00000000f, 0.00000000f, 0.00000000f
};

static const float s_intercept = 0.24986274f;

float lgbm_predict_proba(const float *features, int n_features)
{
    float z;
    float x;
    float scale;
    int   i;

    (void)n_features;
    z = s_intercept;
    for(i = 0; i < LGBM_N_FEATURES; i++)
    {
        scale = s_scale[i];
        if(scale < 1e-6f)
        {
            scale = 1.0f;
        }
        x = (features[i] - s_mean[i]) / scale;
        z += s_coef[i] * x;
    }
    if(z >= 0.0f)
    {
        return 1.0f / (1.0f + expf(-z));
    }
    {
        float ez = expf(z);
        return ez / (1.0f + ez);
    }
}
